DROP DOMAIN PAGAMENTO CASCADE; 
DROP DOMAIN CONSEGNA CASCADE;
DROP DOMAIN TIPOLOGIACLIENTE CASCADE;
DROP TABLE Canzone CASCADE;
DROP TABLE CD CASCADE;
DROP TABLE INVENTARIO CASCADE;
DROP TABLE MUSICISTAAUTORE CASCADE;
DROP TABLE MUSICISTASUONAIN CASCADE;
DROP TABLE MUSICISTA CASCADE;
DROP TABLE STRUMENTO CASCADE;
DROP TABLE VENDITA CASCADE;
DROP TABLE IMMAGINE CASCADE;
DROP TABLE Cliente CASCADE;
DROP TABLE STRUMENTODAMUSICISTA CASCADE;
DROP TABLE CONTENUTOVENDITA CASCADE;
		
